# Generated by Django 3.2.17 on 2023-02-05 19:31
import core.models
import django.db.models.deletion
import quote.utils
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Quote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("buyer_first_name", models.CharField(max_length=255)),
                ("buyer_last_name", models.CharField(max_length=255)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("CA", "California"),
                            ("TX", "Texas"),
                            ("NY", "New York"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "flat_cost_coverages",
                    core.models.DataClassField(
                        dataClass=core.models.QuoteFlatCostCoverages,
                        encoder=quote.utils.EnhancedJSONEncoder,
                    ),
                ),
                (
                    "percentage_cost_coverages",
                    core.models.DataClassField(
                        dataClass=core.models.QuotePercentageCostCoverages,
                        encoder=quote.utils.EnhancedJSONEncoder,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
