# Generated by Django 3.2.17 on 2023-02-05 20:45
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_quote"),
    ]

    operations = [
        migrations.AddField(
            model_name="quote",
            name="monthly_subtotal",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name="quote",
            name="monthly_taxes",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name="quote",
            name="monthly_total",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
    ]
